In [1]:
import numpy as np
arr=np.arange(10,31)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [7]:
# slicing thru arrays

In [2]:
arr[3:]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30])

In [3]:
arr[::-1]

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10])

In [4]:
arr[7:10]

array([17, 18, 19])

In [5]:
arr[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [6]:
arr[:4]

array([10, 11, 12, 13])

In [8]:
arr[::4]

array([10, 14, 18, 22, 26, 30])

In [9]:
arr[2::2]

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [10]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [11]:
part1=arr[4:10]

In [12]:
part1

array([14, 15, 16, 17, 18, 19])

In [16]:
# replace all the arrary values with integer 89 in part1
part1[:]=89

In [17]:
part1

array([89, 89, 89, 89, 89, 89])

In [18]:
# print the array
arr

array([10, 11, 12, 13, 89, 89, 89, 89, 89, 89, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [22]:
part2=arr[-1::]

In [23]:
part2

array([30])

In [24]:
part2[:]=20

In [25]:
part2

array([20])

In [26]:
arr

array([10, 11, 12, 13, 89, 89, 89, 89, 89, 89, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 20])

 so v can make changes to array without affecting the original array,
 v use copy() method.

In [30]:
copyarr=arr.copy()

In [31]:
copyarr[:]=67

In [32]:
copyarr

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67,
       67, 67, 67, 67])

In [33]:
arr

array([10, 11, 12, 13, 89, 89, 89, 89, 89, 89, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 20])

here we copied array values to copyarr and later updated 
it with value. bt it doesnt affect the our original array.

In [35]:
part3=arr.copy()

In [37]:
part4=part3[5:10]

In [39]:
part4[:]=98

In [40]:
part4

array([98, 98, 98, 98, 98])

In [41]:
arr

array([10, 11, 12, 13, 89, 89, 89, 89, 89, 89, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 20])