# NUMPY EXERCISE

In [2]:
import numpy as np

In [5]:
mylist=[4,5,6,7]
mylist

[4, 5, 6, 7]

In [12]:
# converting list to 1D array
new=np.array(mylist)
new

array([4, 5, 6, 7])

In [11]:
# accessing an array value 
new[1]

5

In [16]:
# slicing thru array
new[1:3]

array([5, 6])

In [14]:
mytwolist=[[4,5,6,7],[56,8,19,10],[57,19,2,3]]

In [29]:
mytwolist

[[4, 5, 6, 7], [56, 8, 19, 10], [57, 19, 2, 3]]

In [15]:
# pass list as argument
twodarray=np.array(mytwolist)
twodarray

array([[ 4,  5,  6,  7],
       [56,  8, 19, 10],
       [57, 19,  2,  3]])

In [16]:
type(twodarray)

numpy.ndarray

In [37]:
# accesing values from 2d array
twodarray[0][0]

4

In [38]:
twodarray[0][1]

5

In [39]:
twodarray[1][3]

10

In [40]:
twodarray[2][2]

2

In [43]:
# creating a 1d array using arange() method
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [49]:
np.arange(1,10)[3]

4

In [53]:
# reversing an array
np.arange(1,100)[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [56]:
# create an from 1 to 100 by skipping 5 numbers thru array
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [58]:
# slicing from an array
np.arange(1,10)[2:7]

array([3, 4, 5, 6, 7])

In [59]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [65]:
# creating 1D array of zeros
np.zeros(3)

array([0., 0., 0.])

In [67]:
# creating 2D array of zeros
# pass tuple as argument saying no of rows and columns needed
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
# # creating 1D array of ones
np.ones(3)

array([1., 1., 1.])

In [69]:
# creating 2D array of ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
# sample
data=[[4,5,6],[40,46,29],[3,1,10]]
np.array(data)

array([[ 4,  5,  6],
       [40, 46, 29],
       [ 3,  1, 10]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# using functions to return an array
def get_array(data):
    arr=np.array(data)
    return arr 
data=[[4,5,6],[40,46,29],[3,1,10]]
get_array(data)

array([[ 4,  5,  6],
       [40, 46, 29],
       [ 3,  1, 10]])

In [25]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [20]:
# can have floating point values in array
np.arange(2,6,.2) 

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8])

In [22]:
# we want to create an array of 6 numbers from 2 to 5
np.linspace(2,5,6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

In [23]:
np.linspace(10,20,100)
# 100 numbers from 10 to 20

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96

In [27]:
# printing an 4*4 identity matrix 
# two methods - np.eye() and np.identity()

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# numpy.random.rand()
s
rand() - to get random samples of uniform distribution over 0,1

Create an array of given shape and provide it with random samples from a uniform distribution over (0, 1).

uniform distribution of (0,1) can take continuous values b/w 0 and 1
eg, 0,0.1,0.12,...0.3,...
uniform distribution also called continous probalitiy distribution,


simply we can say it returns random values b/w 0 and 1 for the given shape

In [42]:
# here we create a 4*4 matrix with random sample of uniform distributiono over (0,1)
new=np.random.rand(4,4)
new


array([[0.70406935, 0.81868412, 0.24903138, 0.16283922],
       [0.64197209, 0.45755979, 0.06640628, 0.62831814],
       [0.16785854, 0.90223123, 0.96786796, 0.22691471],
       [0.78329927, 0.04060424, 0.26358884, 0.26149922]])

In [43]:
np.random.rand(3)

array([0.43163464, 0.63676185, 0.33727905])

In [45]:
# randn() -for normal distribution

np.random.randn(4,4)

array([[-0.26858614,  0.87542499,  0.09849471,  0.04089717],
       [ 0.32979292,  1.37806861, -1.48082375, -0.51796853],
       [-0.88662201,  0.12575065, -0.00937861, -0.55121899],
       [ 0.40599625,  0.37997366, -0.76955617, -1.51539113]])